"""Obsidian template management and export."""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any, Optional

from hakua_memory.config import ObsidianConfig

# ── Default Templates ────────────────────────────────────────────────

DEFAULT_DIARY_TEMPLATE = """# {{title}}

> Date: {{date}}
> Type: Diary

{{content}}

---
*Generated by hakua-memory*
"""

DEFAULT_DREAM_TEMPLATE = """# {{title}}

> Date: {{date}}
> Type: Dream
> Source: Ebbinghaus sleep cycle

{{content}}

---
*Generated by hakua-memory*
"""

DEFAULT_SLEEP_LOG_TEMPLATE = """# 睡眠ログ {{month}}

## 概要
- レビュー対象: {{review_count}}件の記憶
- 再練習対象: {{rehearsal_count}}件
- 忘却対象: {{forget_count}}件
- 記憶圧縮率: {{compression_rate:.1%}}

## 再練習された記憶
{{rehearsal_list}}

## 忘却された記憶
{{forgotten_list}}

## 洞察
{{insights}}

## Ebbinghaus 忘却曲線
{{forgetting_curve}}

---
*Generated by hakua-memory*
"""

DEFAULT_GRAPH_TEMPLATE = """# セマンティックグラフ {{month}}

## ノード統計
- 総ノード数: {{node_count}}
- アクティブ: {{active_count}}
- 候補: {{candidate_count}}
- 却下: {{rejected_count}}

## 主要ノード
{{top_nodes}}

## グラフ可視化
{{mermaid_graph}}

---
*Generated by hakua-memory*
"""


class ObsidianTemplateRenderer:
    """Renders Obsidian-compatible markdown from templates."""

    def __init__(self, config: Optional[ObsidianConfig] = None) -> None:
        self.config = config or ObsidianConfig()
        self.templates = {
            "diary": self.config.diary_template or DEFAULT_DIARY_TEMPLATE,
            "dream": self.config.dream_template or DEFAULT_DREAM_TEMPLATE,
            "sleep_log": self.config.sleep_log_template or DEFAULT_SLEEP_LOG_TEMPLATE,
            "graph": DEFAULT_GRAPH_TEMPLATE,
        }

    def render(self, template_name: str, **kwargs: Any) -> str:
        """Render a template with given context."""
        template = self.templates.get(template_name, "")
        if not template:
            return ""

        # Add default context
        context = {
            "date": datetime.now(timezone.utc).strftime("%Y-%m-%d"),
            "month": datetime.now(timezone.utc).strftime("%Y-%m"),
        }
        context.update(kwargs)

        # Simple template substitution
        result = template
        for key, value in context.items():
            placeholder = "{{" + key + "}}"
            result = result.replace(placeholder, str(value))

        return result

    def render_sleep_log(
        self,
        review_count: int,
        rehearsal_count: int,
        forget_count: int,
        rehearsal_list: list[str],
        forgotten_list: list[str],
        insights: list[str],
        forgetting_curve: str = "",
    ) -> str:
        """Render sleep log template."""
        compression_rate = (
            (review_count - forget_count) / review_count if review_count > 0 else 1.0
        )
        return self.render(
            "sleep_log",
            review_count=review_count,
            rehearsal_count=rehearsal_count,
            forget_count=forget_count,
            compression_rate=compression_rate,
            rehearsal_list="\n".join(f"- {r}" for r in rehearsal_list) or "（なし）",
            forgotten_list="\n".join(f"- {f}" for f in forgotten_list) or "（なし）",
            insights="\n".join(f"- {i}" for i in insights) or "（なし）",
            forgetting_curve=forgetting_curve or "（プロットなし）",
        )

    def render_graph_summary(
        self,
        node_count: int,
        active_count: int,
        candidate_count: int,
        rejected_count: int,
        top_nodes: list[dict[str, Any]],
        mermaid_graph: str = "",
    ) -> str:
        """Render graph summary template."""
        top_nodes_str = "\n".join(
            f"- [{n.get('status', 'unknown')}] {n.get('label', n.get('node_id', 'unknown'))}"
            for n in top_nodes[:10]
        )
        return self.render(
            "graph",
            node_count=node_count,
            active_count=active_count,
            candidate_count=candidate_count,
            rejected_count=rejected_count,
            top_nodes=top_nodes_str or "（ノードなし）",
            mermaid_graph=mermaid_graph or "（グラフなし）",
        )


def generate_mermaid_graph(nodes: list[dict[str, Any]], edges: list[dict[str, Any]]) -> str:
    """Generate Mermaid graph syntax from nodes and edges."""
    lines = ["graph TD", "    %% Generated by hakua-memory"]

    # Add nodes with styles
    for node in nodes[:20]:  # Limit to 20 nodes for readability
        node_id = node.get("node_id", "unknown").replace("-", "_")
        label = node.get("label", node_id)[:20]
        status = node.get("status", "unknown")

        # Style based on status
        if status == "accepted":
            lines.append(f'    {node_id}["{label}"]:::accepted')
        elif status == "asserted":
            lines.append(f'    {node_id}["{label}"]:::asserted')
        elif status == "candidate":
            lines.append(f'    {node_id}["{label}"]:::candidate')
        else:
            lines.append(f'    {node_id}["{label}"]')

    # Add class definitions
    lines.append("    classDef accepted fill:#9f9,stroke:#333,stroke-width:2px")
    lines.append("    classDef asserted fill:#9cf,stroke:#333,stroke-width:2px")
    lines.append("    classDef candidate fill:#fcc,stroke:#333,stroke-width:1px")

    # Add edges
    for edge in edges[:15]:  # Limit to 15 edges
        source = edge.get("source", "").replace("-", "_")
        target = edge.get("target", "").replace("-", "_")
        rel = edge.get("relationship", "relates_to")[:15]
        if source and target:
            lines.append(f"    {source} -->|{rel}| {target}")

    return "\n".join(lines)


def generate_forgetting_curve_mermaid(
    intervals: list[int],
    retention_rates: list[float],
) -> str:
    """Generate Mermaid XY chart for forgetting curve."""
    lines = [
        "xychart-beta",
        "    title Ebbinghaus Forgetting Curve",
        "    x-axis [hours] " + ", ".join(str(i) for i in intervals),
        "    y-axisRetention Rate",
    ]
    # Add data
    data = ", ".join(f"{r:.2f}" for r in retention_rates)
    lines.append(f"    line [{data}]")
    return "\n".join(lines)
