"""Test Obsidian template management."""

from __future__ import annotations

from hakua_memory.obsidian.templates import (
    ObsidianTemplateRenderer,
    generate_forgetting_curve_mermaid,
    generate_mermaid_graph,
)


def test_default_templates() -> None:
    """Test default template rendering."""
    renderer = ObsidianTemplateRenderer()
    result = renderer.render("diary", title="Test Diary", content="Test content")
    assert "Test Diary" in result
    assert "Test content" in result
    assert "Generated by hakua-memory" in result
    print("✅ Default diary template: PASSED")


def test_sleep_log_template() -> None:
    """Test sleep log template."""
    renderer = ObsidianTemplateRenderer()
    result = renderer.render_sleep_log(
        review_count=100,
        rehearsal_count=20,
        forget_count=5,
        rehearsal_list=["Memory A", "Memory B"],
        forgotten_list=["Memory C"],
        insights=["Insight 1"],
        forgetting_curve="[curve]",
    )
    assert "レビュー対象: 100件" in result
    assert "再練習対象: 20件" in result
    assert "忘却対象: 5件" in result
    assert "Memory A" in result
    assert "Memory C" in result
    assert "Insight 1" in result
    assert "[curve]" in result
    print("✅ Sleep log template: PASSED")


def test_graph_template() -> None:
    """Test graph summary template."""
    renderer = ObsidianTemplateRenderer()
    nodes = [
        {"node_id": "n1", "label": "Node 1", "status": "accepted"},
        {"node_id": "n2", "label": "Node 2", "status": "asserted"},
    ]
    result = renderer.render_graph_summary(
        node_count=2,
        active_count=1,
        candidate_count=1,
        rejected_count=0,
        top_nodes=nodes,
        mermaid_graph="[graph]",
    )
    assert "Node 1" in result
    assert "Node 2" in result
    assert "[graph]" in result
    print("✅ Graph template: PASSED")


def test_mermaid_graph_generation() -> None:
    """Test Mermaid graph generation."""
    nodes = [
        {"node_id": "claim-1", "label": "Release", "status": "accepted"},
        {"node_id": "claim-2", "label": "Budget", "status": "asserted"},
    ]
    edges = [
        {"source": "claim-1", "target": "claim-2", "relationship": "depends_on"},
    ]
    graph = generate_mermaid_graph(nodes, edges)
    assert "graph TD" in graph
    assert "claim_1" in graph
    assert "claim_2" in graph
    assert "depends_on" in graph
    print("✅ Mermaid graph generation: PASSED")


def test_forgetting_curve_mermaid() -> None:
    """Test forgetting curve Mermaid generation."""
    intervals = [1, 2, 6, 12, 24]
    rates = [0.95, 0.85, 0.65, 0.45, 0.30]
    result = generate_forgetting_curve_mermaid(intervals, rates)
    assert "xychart-beta" in result
    assert "1, 2, 6, 12, 24" in result
    assert "0.95" in result
    print("✅ Forgetting curve Mermaid: PASSED")


if __name__ == "__main__":
    test_default_templates()
    test_sleep_log_template()
    test_graph_template()
    test_mermaid_graph_generation()
    test_forgetting_curve_mermaid()
    print("\n★ ALL OBSIDIAN TEMPLATE TESTS PASSED ★")
